using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using RP0.Tests.ReusabilityTests.Config;
using RP0.Tests.ReusabilityTests.Fixtures;

namespace RP0.Tests.ReusabilityTests
{
    /// <summary>
    /// Renders the balance table for one tech tier as markdown.
    ///
    /// All figures are rounded to four significant digits so that the golden files diff on
    /// real balance changes rather than on floating-point noise.
    /// </summary>
    public static class ReusabilityTable
    {
        public static string Render(TechTier tier)
        {
            var sb = new StringBuilder();

            sb.AppendLine($"# Reusability balance table - {tier.Name} tier");
            sb.AppendLine();
            sb.AppendLine($"Era: {tier.Era}");
            sb.AppendLine();
            sb.AppendLine("Generated by `RP0.Tests` (`ReusabilityTests/RecoveryTableTests.cs`). Do not hand-edit:");
            sb.AppendLine("re-run `dotnet test` and promote the generated `.received.md` when a change is intended.");
            sb.AppendLine();
            AppendSettings(sb, tier);
            sb.AppendLine();
            AppendAssumptions(sb);
            sb.AppendLine();
            AppendIntentGaps(sb);
            sb.AppendLine();
            AppendBuildTable(sb, tier);
            sb.AppendLine();
            AppendReuseTable(sb, tier);
            sb.AppendLine();
            AppendDesignTargets(sb, tier);

            return sb.ToString();
        }

        /// <summary>
        /// Target versus actual for the refurbishment durations the PR states it is aiming at.
        /// Reported rather than asserted - see Fixtures/DesignTargets.cs.
        /// </summary>
        private static void AppendDesignTargets(StringBuilder sb, TechTier tier)
        {
            sb.AppendLine("## Versus the PR's stated design targets");
            sb.AppendLine();

            var rows = DesignTargets.ForTier(tier).ToList();
            if (rows.Count == 0)
            {
                sb.AppendLine("No stated target applies at this tier.");
                return;
            }

            sb.AppendLine("Quoted from the header comment of `GameData/RP-1/SCMData/RefurbishmentLevels.cfg`");
            sb.AppendLine("and the doc comment on `Formula.GetRefurbishmentBP`.");
            sb.AppendLine();
            sb.AppendLine("| Vessel | effCost | vessel cost | build BP | refurb BP | refurb cost | refurb/vessel cost | engineers | target (d) | actual (d) | actual/target | source |");
            sb.AppendLine("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |");

            foreach (var row in rows)
            {
                FormulaInputs v = row.Key.At(tier);
                int engs = Staffing.MaxEngineers(v, Vessels.HangarSizeSqrMagnitude);
                double refurbBP = Formula.RefurbishmentBP(v);
                double refurbCost = Formula.RefurbishmentCost(v);
                double actual = Staffing.DaysAt(refurbBP, engs);
                double ratio = actual / row.Value.Days;

                sb.AppendLine($"| {row.Key.Name} | {Sig(v.EffectiveCost)} | {Sig(v.Cost)} | {Sig(v.BuildPoints)} | " +
                              $"{Sig(refurbBP)} | {Sig(refurbCost)} | {Sig(refurbCost / v.Cost)} | " +
                              $"{engs.ToString(CultureInfo.InvariantCulture)} | " +
                              $"{Sig(row.Value.Days)} | {Sig(actual)} | {Sig(ratio)}x | {row.Value.Source} |");
            }
        }

        private static void AppendSettings(StringBuilder sb, TechTier tier)
        {
            RecoverySettings s = tier.Settings;
            sb.AppendLine("## Multipliers in effect");
            sb.AppendLine();
            sb.AppendLine("Parsed from `GameData/RP-1/SCMData/RecoveryLevels.cfg` and `RefurbishmentLevels.cfg`.");
            sb.AppendLine();
            sb.AppendLine("| Setting | Value |");
            sb.AppendLine("| --- | ---: |");
            sb.AppendLine($"| Researched techs | {(tier.ResearchedTechs.Count == 0 ? "(none)" : string.Join(", ", tier.ResearchedTechs))} |");
            sb.AppendLine($"| RecoveryRateMult (m/s) | {Sig(s.RecoveryRateMult)} |");
            sb.AppendLine($"| RecoveryCostMult (funds/tonne-m) | {Sig(s.RecoveryCostMult)} |");
            sb.AppendLine($"| RefurbishmentRateMult | {Sig(s.RefurbishmentRateMult)} |");
            sb.AppendLine($"| RefurbishmentCostMult | {Sig(s.RefurbishmentCostMult)} |");
            sb.AppendLine($"| SplashdownPenaltyMult | {Sig(s.SplashdownPenaltyMult)} |");
            sb.AppendLine($"| salaryEngineers | {Sig(s.SalaryEngineers)} |");
        }

        private static void AppendAssumptions(StringBuilder sb)
        {
            sb.AppendLine("## Assumptions");
            sb.AppendLine();
            sb.AppendLine("- Durations use `LaunchComplex.MaxEngineers` (a fully staffed complex), so every");
            sb.AppendLine("  engineer-driven duration below is a best case.");
            sb.AppendLine("- Pad and hangar staffing scale differently, which is why the SPH rows all show the");
            sb.AppendLine("  same engineer count. `LaunchComplex.RawMaxEngineers` uses `massMax^0.75` for pads,");
            sb.AppendLine("  but a hangar's massMax is `float.MaxValue`, so it falls back to");
            sb.AppendLine("  `sizeMax.sqrMagnitude * 0.01`. `LCData.StartingHangar` is fixed at (40, 10, 40) and");
            sb.AppendLine("  nothing ever changes it, so every SPH vessel gets 495 engineers regardless of size,");
            sb.AppendLine("  while a pad built for the vessel scales with it (129 for a 30 t pad, 3322 for 2300 t).");
            sb.AppendLine("  The per-project cap `MaxEngineersFor` blends mass and BP, but it can only lower that");
            sb.AppendLine("  ceiling: it binds for small SPH craft (jet X-plane 134, X-15 243) and is inert for the");
            sb.AppendLine("  orbiter, which is sized for 2681 but capped at the hangar's 495.");
            sb.AppendLine($"- `RP0Settings.BuildRate` held at {Sig(Staffing.BuildRateSetting)} (Normal difficulty).");
            sb.AppendLine("- Recovery is not engineer-driven: its BP is the distance from KSC in metres,");
            sb.AppendLine("  consumed at `RecoveryRateMult` m/s.");
            sb.AppendLine("- `legacy recovery` reproduces the pre-#2825 model for comparison; it *was*");
            sb.AppendLine("  engineer-driven, so its duration uses the same staffing as integration.");
            sb.AppendLine("- Vessel cost/effectiveCost provenance is documented in `Fixtures/Vessels.cs`.");
        }

        /// <summary>
        /// These tables model the formulas as INTENDED. Two of the branches they exercise do
        /// not fire in the shipped game because of how LandedAt is matched. Called out up
        /// front so nobody reads a refurbishment figure below as what a player experiences
        /// today.
        /// </summary>
        private static void AppendIntentGaps(StringBuilder sb)
        {
            sb.AppendLine("## Read this before the numbers: intent vs shipped behaviour");
            sb.AppendLine();
            sb.AppendLine("These tables model the formulas as **intended**. Two branches they exercise never");
            sb.AppendLine("fire in the shipped game, because `Formula.VesselInputs` derives `splashed` and");
            sb.AppendLine("`atKSC` by substring-matching `VesselProject.LandedAt`, which is assigned from");
            sb.AppendLine("`Vessel.landedAt` (`KCTUtilities.RecoverActiveVesselToStorage`). That field holds");
            sb.AppendLine("launch-site and static names, not situation names.");
            sb.AppendLine();
            sb.AppendLine("Measured across a real RP-1 career save (55,603 `landedAt` values):");
            sb.AppendLine();
            sb.AppendLine("| observed value | count | matched by |");
            sb.AppendLine("| --- | ---: | --- |");
            sb.AppendLine("| *(empty)* | 55,210 | nothing |");
            sb.AppendLine("| `#autoLOC_*` localisation tokens | 290 | nothing |");
            sb.AppendLine("| `LaunchPad` | 51 | **nothing** - the test is `Contains(\"Launchpad\")`, lowercase p |");
            sb.AppendLine("| `KSC_Runway_09` | 42 | `Contains(\"Runway\")` |");
            sb.AppendLine("| `Moho` | 6 | nothing |");
            sb.AppendLine("| `KSC_LaunchPad_Platform` | 3 | **nothing** - same casing mismatch |");
            sb.AppendLine("| `Runway` | 1 | `Contains(\"Runway\")` |");
            sb.AppendLine();
            sb.AppendLine("- **Splashdown is dead.** `\"Splashdown\"` occurs in none of those values, while");
            sb.AppendLine("  `splashed = True` occurs 2,142 times in the same save. So the 1.5x penalty never");
            sb.AppendLine("  applies and the three `SplashdownPenaltyMult` TECH nodes in");
            sb.AppendLine("  `RefurbishmentLevels.cfg` tune a value that is never read. Every row marked");
            sb.AppendLine("  Splashdown below shows refurbishment BP 1.5x higher than a player would see.");
            sb.AppendLine("- **Pad landings miss the at-KSC discount.** The codebase uses `\"LaunchPad\"`");
            sb.AppendLine("  everywhere else (22 occurrences vs 2 of `\"Launchpad\"`, both introduced here), so");
            sb.AppendLine("  the `Reusable booster, RTLS` row is shown 0.8x lower than it would be in game.");
            sb.AppendLine("- **Runway works by luck**, because `KSC_Runway_09` happens to contain the substring.");
            sb.AppendLine();
            sb.AppendLine("Fixing this means capturing `Vessel.Splashed` at recovery rather than parsing a");
            sb.AppendLine("display string, and correcting the `LaunchPad` casing.");
        }

        private static void AppendBuildTable(StringBuilder sb, TechTier tier)
        {
            sb.AppendLine("## Build and rollout");
            sb.AppendLine();
            sb.AppendLine("| Vessel | LC | HR | mass (t) | cost | effCost | EC/cost | engineers | build BP | build (d) | rollout BP | rollout cost |");
            sb.AppendLine("| --- | :-: | :-: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");

            foreach (VesselArchetype a in Vessels.All)
            {
                FormulaInputs v = a.At(tier);
                int engs = Staffing.MaxEngineers(v, Vessels.HangarSizeSqrMagnitude);

                sb.AppendLine(string.Join(" | ", new[]
                {
                    "| " + a.Name,
                    a.IsSPH ? "SPH" : "VAB",
                    a.HumanRated ? "yes" : "no",
                    Sig(v.Mass),
                    Sig(v.Cost),
                    Sig(v.EffectiveCost),
                    Sig(v.EffectiveCost / v.Cost),
                    engs.ToString(CultureInfo.InvariantCulture),
                    Sig(v.BuildPoints),
                    Sig(Staffing.DaysAt(v.BuildPoints, engs)),
                    Sig(Formula.RolloutBP(v)),
                    Sig(Formula.RolloutCost(v)) + " |",
                }));
            }
        }

        private static void AppendReuseTable(StringBuilder sb, TechTier tier)
        {
            sb.AppendLine("## Recovery and refurbishment");
            sb.AppendLine();
            sb.AppendLine("| Vessel | landed at | dist (km) | recov (d) | recov cost | refurb BP | refurb (d) | refurb cost | refurb/build BP | reuse cost/vessel cost | legacy recov BP | legacy recov (d) |");
            sb.AppendLine("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");

            foreach (VesselArchetype a in Vessels.All)
            {
                FormulaInputs v = a.At(tier);
                int engs = Staffing.MaxEngineers(v, Vessels.HangarSizeSqrMagnitude);

                double refurbBP = Formula.RefurbishmentBP(v);
                double refurbCost = Formula.RefurbishmentCost(v);
                double recovCost = Formula.RecoveryCost(v);
                double legacyBP = LegacyFormula.RecoveryBP(v, a.LandedAt);

                sb.AppendLine(string.Join(" | ", new[]
                {
                    "| " + a.Name,
                    a.LandedAt,
                    Sig(v.KscDistance / 1000d),
                    Sig(Staffing.RecoveryDays(v)),
                    Sig(recovCost),
                    Sig(refurbBP),
                    Sig(Staffing.DaysAt(refurbBP, engs)),
                    Sig(refurbCost),
                    Sig(refurbBP / v.BuildPoints),
                    Sig((recovCost + refurbCost) / v.Cost),
                    Sig(legacyBP),
                    Sig(Staffing.DaysAt(legacyBP, engs)) + " |",
                }));
            }
        }

        /// <summary>
        /// Four significant digits, invariant culture, no exponent below 1e6 so the table stays
        /// readable. Rounding keeps the golden files stable against floating-point noise.
        /// </summary>
        public static string Sig(double value, int digits = 4)
        {
            if (double.IsNaN(value)) return "NaN";
            if (double.IsPositiveInfinity(value)) return "inf";
            if (double.IsNegativeInfinity(value)) return "-inf";
            if (value == 0d) return "0";

            double abs = Math.Abs(value);
            int exp = (int)Math.Floor(Math.Log10(abs));
            double rounded = Math.Round(value / Math.Pow(10, exp - (digits - 1))) * Math.Pow(10, exp - (digits - 1));

            if (abs >= 1e6 || abs < 1e-3)
                return rounded.ToString("0.###e+0", CultureInfo.InvariantCulture);

            int decimals = Math.Max(0, digits - 1 - exp);
            return rounded.ToString("N" + decimals, CultureInfo.InvariantCulture);
        }

        public static IEnumerable<string> Lines(string text) =>
            text.Replace("\r\n", "\n").Split('\n');

        /// <summary>
        /// A readable first-difference report between an approved and a received table.
        /// </summary>
        public static string Diff(string approved, string received, int maxReported = 12)
        {
            string[] a = Lines(approved).ToArray();
            string[] b = Lines(received).ToArray();

            var sb = new StringBuilder();
            int reported = 0;
            for (int i = 0; i < Math.Max(a.Length, b.Length) && reported < maxReported; i++)
            {
                string la = i < a.Length ? a[i] : "<missing>";
                string lb = i < b.Length ? b[i] : "<missing>";
                if (la == lb)
                    continue;

                sb.AppendLine($"  line {i + 1}:");
                sb.AppendLine($"    approved: {la}");
                sb.AppendLine($"    received: {lb}");
                reported++;
            }

            if (reported == maxReported)
                sb.AppendLine("  ... (further differences suppressed)");

            return sb.ToString();
        }
    }
}
